added time-windowing dmd phase.

diff --git a/examples/merlin/heat_conduction_hdf.yaml b/examples/merlin/heat_conduction_hdf.yaml
--- a/examples/merlin/heat_conduction_hdf.yaml
+++ b/examples/merlin/heat_conduction_hdf.yaml
@@ -57,6 +57,7 @@
 #      |- prepare_dir
 #      |- sample_foms
 #      |- test_fom
+#      |- test_rom
 #
 # Each directory corresponds to:
 #   - dmd_data: snapshots for the training/test parameter values
@@ -65,6 +66,7 @@
 #   - prepare_dir: command script/output/error of the step prepare_dir
 #   - sample_foms: command script/output/error of the step sample_foms
 #   - test_fom: command script/output/error of the step test_fom
+#   - test_rom: command script/output/error of the step test_rom
 
 description:
   name: heat_conduction_hdf
@@ -75,6 +77,7 @@ env:
     OUTPUT_PATH: ./heat_conduction_hdf_cases
     ROOT_DIR: $(dirname $(SPECROOT))
     PHYS_EXEC: $(ROOT_DIR)/dmd/parametric_heat_conduction
+    ROM_EXEC: $(ROOT_DIR)/dmd/parametric_tw_csv
     MESH_FILE: $(ROOT_DIR)/data/star.mesh
     LIST_DIR: $(MERLIN_WORKSPACE)/dmd_list
     DATA_DIR: $(MERLIN_WORKSPACE)/dmd_data
@@ -86,6 +89,8 @@ env:
     CY: 0
     TEST_IDX: 4
     TEST_RAD: 0.5
+    NSAMPLE_PER_WINDOW: 25
+    DTC: 0.01
 
 batch:
    type: local
@@ -150,6 +155,33 @@ study:
       depends: [prepare_dir,sample_foms_*]
       task_queue: sample_queue
 
+  - name: test_rom
+    description: Offline phase of time-windowing parametric DMD
+    run:
+      cmd: |
+        $(LAUNCHER) $(ROM_EXEC) -list $(LIST_DIR) -data $(DATA_DIR) -o hc_parametric_tw -nwinsamp $(NSAMPLE_PER_WINDOW) -dtc $(DTC) -offline -hdf
+
+        if [ $? -ne 0 ]; then
+           echo "offline_rom failed."
+           exit -1
+        else
+           echo "offline_rom succeeded."
+        fi
+
+        $(LAUNCHER) $(ROM_EXEC) -list $(LIST_DIR) -data $(DATA_DIR) -o hc_parametric_tw -nwinsamp $(NSAMPLE_PER_WINDOW) -dtc $(DTC) -online -hdf
+
+        if [ $? -ne 0 ]; then
+           echo "online_rom failed."
+           exit -1
+        else
+           echo "online_rom succeeded."
+        fi
+
+      nodes: 1
+      procs: 1
+      depends: [prepare_dir,sample_foms_*,test_fom]
+      task_queue: sample_queue
+
 ########################################
 # Worker and sample configuration
 ########################################
@@ -169,6 +201,11 @@ merlin:
       testworkers:
         args: --concurrency 1 --prefetch-multiplier 1
         steps: [test_fom]
+        nodes: 1
+        machines: [quartz]
+      romworkers:
+        args: --concurrency 1 --prefetch-multiplier 1
+        steps: [test_rom]
         nodes: 1
         machines: [quartz]
 
